FoodHut/FoodHut.MVC/Controllers/HomeController.cs
using FoodHut.BL.Services.Abstractions;
using FoodHut.BL.Services.Implementations;
using FoodHut.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FoodHut.MVC.Controllers
{
    public class HomeController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly IProductService _productService;
        readonly IReviewService _reviewService;
        readonly IRestaurantService _restaurantService;
        readonly ISettingService _settingService;

        public HomeController(IProductService productService, ICategoryService categoryService, IReviewService reviewService, IRestaurantService restaurantService, ISettingService settingService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _reviewService = reviewService;
            _restaurantService = restaurantService;
            _settingService = settingService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                HomeVM VM = new()
                {
                    Categories = await _categoryService.GetCategoryViewItemsAsync(),
                    Products = await _productService.GetViewItemsAsync(),
                    Reviews = await _reviewService.GetViewItemsAsync(),
                    Settings = await _settingService.GetSettingsAsync()
                };
                // Burada restoran siyahısını doldururuq
                var restaurants = await _restaurantService.GetAllAsync();
                ViewData["Restaurants"] = new SelectList(restaurants, "Id", "Name");
                return View(VM);
            }
            catch (Exception)
            {
                return BadRequest("Something went wrong!");
            }
        }
    }
}

FoodHut/FoodHut.MVC/Controllers/ReservationController.cs
using FoodHut.BL.DTOs;
using FoodHut.BL.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace FoodHut.MVC.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _service;

        public ReservationController(IReservationService service)
        {
            _service = service;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReservationDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            await _service.CreateReservationAsync(dto);
            await _service.SaveChangesAsync();

            // Əgər istifadəçi admindirsə, admin panelinə yönləndir
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "AdminReservation", new { area = "Admin" });
            }

            // Müştəri üçün Success səhifəsinə yönləndir
            return RedirectToAction("Success");
        }



        public IActionResult Success()
        {
            return View(); // Müştəri uğurlu rezervasiya etdikdə bu səhifə açılacaq
        }
    }
}

FoodHut/FoodHut.MVC/Controllers/ReviewController.cs
using FoodHut.BL.DTOs;
using FoodHut.BL.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace FoodHut.MVC.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewService _reviewService;
        private readonly IRestaurantService _restaurantService;

        public ReviewController(IReviewService reviewService, IRestaurantService restaurantService)
        {
            _reviewService = reviewService;
            _restaurantService = restaurantService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var restaurants = await _restaurantService.GetAllAsync();
            ViewData["Restaurants"] = new SelectList(restaurants, "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserCreateDto dto)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Unauthorized();
            }

          

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }

            await _reviewService.UserCreateAsync(dto,
                User.FindFirst(ClaimTypes.NameIdentifier)?.Value,
                User.Identity.Name,
                User.FindFirst(ClaimTypes.Role)?.Value
            );
            await _reviewService.SaveChangesAsync();

            TempData["SuccessMessage"] = "Your review has been submitted successfully!";
            return RedirectToAction("Index", "Home");
        }
    }
}

FoodHut/FoodHut.MVC/Views/Home/Index.cshtml
@model HomeVM;

  <!--  About Section  -->
<div id="about" class="container-fluid wow fadeIn"  data-wow-duration="1.5s">
    <div class="row">
        <div class="col-lg-6 has-img-bg"></div>
        <div class="col-lg-6">
            <div class="row justify-content-center">
                <div class="col-sm-8 py-5 my-5">
                    <h2 class="mb-4">About Us</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, quisquam accusantium nostrum modi, nemo, officia veritatis ipsum facere maxime assumenda voluptatum enim! Labore maiores placeat impedit, vero sed est voluptas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita alias dicta autem, maiores doloremque quo perferendis, ut obcaecati harum, <br><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum necessitatibus iste,
                        nulla recusandae porro minus nemo eaque cum repudiandae quidem voluptate magnam voluptatum? <br>Nobis, saepe sapiente omnis qui eligendi pariatur. quis voluptas. Assumenda facere adipisci quaerat. Illum doloremque quae omnis vitae.
                    </p>
                    <p><b>Lonsectetur adipisicing elit. Blanditiis aspernatur, ratione dolore vero asperiores explicabo.</b></p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos ab itaque modi, reprehenderit fugit soluta, molestias optio repellat incidunt iure sed deserunt nemo magnam rem explicabo vitae. Cum, nostrum, quidem.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  gallary Section  -->
<div id="gallary" class="text-center bg-dark text-light has-height-md middle-items wow fadeIn">
    <h2 class="section-title">OUR MENU</h2>
</div>
<div class="gallary row">
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-1.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">       
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-2.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">  
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-3.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-4.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
        <a href="#" class="gallary-overlay"></a>
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-5.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-6.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-7.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-8.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-9.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-10.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-11.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
    <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
        <img src="~/assets/imgs/gallary-12.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
    </div>
</div>

<!-- book a table Section  -->
<div class="container-fluid has-bg-overlay text-center text-light has-height-lg middle-items" id="book-table">
    <div class="">
        <h2 class="section-title mb-5">BOOK A TABLE</h2>
        <div class="row mb-5">
            <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                <input type="email" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="EMAIL">
            </div>
            <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                <input type="number" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="NUMBER OF GUESTS" max="20" min="0">
            </div>
            <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                <input type="time" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="EMAIL">
            </div>
            <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                <input type="date" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="12/12/12">
            </div>
        </div>
        <a  class="btn btn-lg btn-primary" id="rounded-btn"  asp-controller="Reservation" asp-action="Create">FIND TABLE</a>
    </div>
</div>



@if (Model.Categories.Count > 0)
{
    <!-- BLOG Section  -->
    <div id="blog" class="container-fluid bg-dark text-light py-5 text-center wow fadeIn">
        <h2 class="section-title py-5">EVENTS AT THE FOOD HUT</h2>
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-4 mb-5">
                <ul class="nav nav-pills nav-justified mb-3" id="pills-tab" role="tablist">
                    @foreach (CategoryViewItemDto category in Model.Categories)
                    {
                        <li class="nav-item">
                            <button class="nav-link category-btn" data-category="@category.Id" role="tab" onclick="loadProducts(@category.Id)" style="background-color: #FF214F; color: white; border: none; padding: 10px 20px; cursor: pointer;">
                                @category.Name
                            </button>
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="categories">
            <!-- Bu hissəni AJAX vasitəsilə göstəririk, amma səhifə başlanğıcında göstərilə bilər -->
        </div>

        <!-- Məhsullar bu div-in içində göstəriləcək -->
        <div id="products-container"></div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <script>
            function loadProducts(categoryId) {
                $.ajax({
                    url: "/Product/ProductsByCategory",
                    type: "GET",
                    data: { categoryId: categoryId },
                    success: function (data) {
                        $("#products-container").html(data); // Gələn HTML-i səhifəyə əlavə edirik
                    },
                    error: function () {
                        alert("An error occurred while retrieving products!");
                    }
                });
            }

            // Səhifə yükləndikdə avtomatik olaraq "Foods" category'sinin məhsullarını yükləyirik
            $(document).ready(function () {
                var foodsCategory = @Model.Categories.FirstOrDefault(c => c.Name == "Foods")?.Id;
                if (foodsCategory) {
                    loadProducts(foodsCategory);
                }
            });
        </script>
    </div>
}



<!-- Review Section  -->

@if (User.Identity.IsAuthenticated)
{
    <form asp-action="Create" asp-controller="Review" method="post" style="max-width: 500px; margin: 0 auto; padding: 20px; background-color: #3a3a3a; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
        <h3 style="text-align: center; margin-bottom: 20px; color: #fff;">Write a Review</h3>

        <label style="font-weight: bold; color: #fff;">Select Restaurant:</label>
        @if (ViewData["Restaurants"] != null)
        {
            <select name="RestaurantId" class="form-control" required style="width: 100%; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 15px; background-color: #d3d3d3; color: black; font-weight: bold;">
                <option value="">-- Select a Restaurant --</option>
                @foreach (var restaurant in (IEnumerable<SelectListItem>)ViewData["Restaurants"])
                {
                    <option value="@restaurant.Value">@restaurant.Text</option>
                }
            </select>
        }
        else
        {
            <p style="color: red;">No restaurants available.</p>
        }

        <label style="font-weight: bold; color: #fff;">Rating (1-5):</label>
        <input type="number" name="Rating" min="1" max="5" required class="form-control" style="width: 100%; padding: 12px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 15px; background-color: #d3d3d3; color: black; font-weight: bold;">

        <label style="font-weight: bold; color: #fff;">Your Review:</label>
        <textarea name="Comment" required class="form-control" style="width: 100%; padding: 12px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 15px; height: 150px; background-color: #d3d3d3; color: black; font-weight: bold;"></textarea>

        <button type="submit" class="btn btn-primary mt-2" style="width: 100%; padding: 12px; background-color: #FF214F; border: none; color: white; font-size: 16px; border-radius: 4px; cursor: pointer; transition: background-color 0.3s;">
            Submit Review
        </button>
    </form>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success mt-2" style="text-align: center; background-color: #28a745; color: white; padding: 10px; border-radius: 4px;">
            @TempData["SuccessMessage"]
        </div>
    }
}
else
{
    <p style="text-align: center; color: #fff; font-size: 16px;">
        You must be logged in to write a review.
        <a asp-area="Admin" asp-action="Login" asp-controller="Account" style="color: #FF214F; font-weight: bold;">Login here</a>
    </p>
}

<div id="testmonial" class="container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items">
    <h2 class="section-title my-5 text-center">REVIEWS</h2>
    <div class="row mt-3 mb-5">
        @if (Model.Reviews != null && Model.Reviews.Any())
        {
            @foreach (ReviewViewItemDto review in Model.Reviews)
            {
                <div class="col-md-4 my-3 my-md-0">
                    <div class="testmonial-card">
                        <div>
                            <strong>⭐ @review.Rating</strong>
                        </div>
                        <div class="testmonial-body">
                            <p>@review.Comment</p>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <p style="text-align: center; color: white;">No reviews available.</p>
        }
    </div>
</div>


<!-- CONTACT Section  -->
<div id="contact" class="container-fluid bg-dark text-light border-top wow fadeIn">
    <div class="row">
        <div class="col-12 px-0">
            <div id="map" style="width: 100%; height: 70vh; min-height: 400px;"></div>
        </div>
    </div>
</div>